### PR TITLE
python2/3 compatibility, PySide/PySide2  PyQt4/PyQt5 compatibility, unicode_literals, setup.py

### PR DESCRIPTION
**Pull request by willjp**
# Changes:
## 2x New Dependencies:
- `six`  python2/3 compatibility module
- `Qt.py` Pyside(Qt4)/PySide2(Qt5) compatibility module
## python3-style relative imports

from .module import func
## filter() to list-comprehension

I replaced your use of filter() with list-comprehensions.
In python2 filter() returned a list, in python3 it returns
an iterable. The output was being treated as lists in the code,
so I kept them that way.

### CODE REVIEW

**Comment by drogenlied** [comment]
Python2 sort of works now and I found a few problems while testing: 
- PySide: dragging view with middle mouse button does not work, no error
- PyQt4: AttributeError on every mouse click
- PyQt5: AttributeError on startup due to missing QPainter.drawRoundRect

Python3 works correctly  so far and I can't test PySide2 on either version right now.

**Comment by phtaylor** [comment]
Awesome. Thanks a lot!

**Comment by phtaylor** [comment]
Oops, I think I'll need to revert this merge in favor of the other branch. I'll fix it.

**Comment by phtaylor** [comment]
This merge has now been reverted.

**Pull request merged**
